In [1]:
a = 5 + 3
print(a)   


8


In [2]:
b = 10 - 2
print(b)   


8


In [3]:
c = 4 * 3
print(c)   


12


In [4]:
d = 10 / 3
print(d)   


3.3333333333333335


In [5]:
e = 10 // 3
print(e)   


3


In [6]:
f = 2 ** 3
print(f)   


8


In [7]:
first_name = "John"
last_name = "Doe"
full_name = first_name + " " + last_name
print(full_name)  


John Doe


In [8]:
text = "Hello, World!"
substring = text[7:12]   # Extracts characters from index 7 up to, but not including, index 12
print(substring)  


World


In [9]:
name = "Alice"
age = 30
message = f"Hello, {name}! You are {age} years old."
print(message)  


Hello, Alice! You are 30 years old.


In [10]:
name = "Alice"
age = 30
message = "Hello, {}! You are {} years old.".format(name, age)
print(message)  


Hello, Alice! You are 30 years old.


In [11]:
name = "Alice"
age = 30
message = "Hello, %s! You are %d years old." % (name, age)
print(message)  


Hello, Alice! You are 30 years old.


In [12]:
text = "hello"
uppercase_text = text.upper()
print(uppercase_text)  


HELLO


In [13]:
text = "HELLO"
lowercase_text = text.lower()
print(lowercase_text)  


hello


In [14]:
text = "Hello, World!"
new_text = text.replace("World", "Python")
print(new_text)  


Hello, Python!


In [15]:
text = "Hello, World!"
position = text.find("World")
print(position)  


7


In [16]:
text = "apple,banana,cherry"
fruits = text.split(",")
print(fruits)  


['apple', 'banana', 'cherry']


In [17]:
empty_list = []
print(empty_list)  


[]


In [18]:
numbers = [1, 2, 3, 4, 5]
print(numbers)  # Output: [1, 2, 3, 4, 5]

fruits = ["apple", "banana", "cherry"]
print(fruits)  


[1, 2, 3, 4, 5]
['apple', 'banana', 'cherry']


In [19]:
mixed_list = [1, "hello", 3.14, True]
print(mixed_list)  


[1, 'hello', 3.14, True]


In [20]:
range_list = list(range(1, 6))  # Creates a list of numbers from 1 to 5
print(range_list)  


[1, 2, 3, 4, 5]


In [21]:
squares = [x**2 for x in range(1, 6)]
print(squares)  


[1, 4, 9, 16, 25]


In [22]:
matrix = [[1, 2, 3], [4, 5, 6], [7, 8, 9]]
print(matrix)  


[[1, 2, 3], [4, 5, 6], [7, 8, 9]]


In [23]:
text = "hello"
char_list = list(text)
print(char_list)  


['h', 'e', 'l', 'l', 'o']


In [24]:
tuple_data = (1, 2, 3)
list_data = list(tuple_data)
print(list_data)  


[1, 2, 3]


In [25]:
duplicates = ["apple"] * 3
print(duplicates)  


['apple', 'apple', 'apple']


In [26]:
dynamic_list = []
dynamic_list.append(1)
dynamic_list.append(2)
dynamic_list.append(3)
print(dynamic_list)  


[1, 2, 3]


In [27]:
my_list = [10, 20, 30, 40, 50]
first_element = my_list[0]
print(first_element)  


10


In [28]:
last_element = my_list[-1]
print(last_element)  


50


In [29]:
my_list = [10, 20, 30, 40, 50]
subset = my_list[1:4]
print(subset)  


[20, 30, 40]


In [30]:
start_from_beginning = my_list[:3]
print(start_from_beginning)  


[10, 20, 30]


In [31]:
end_to_last = my_list[2:]
print(end_to_last)  


[30, 40, 50]


In [32]:
last_two_elements = my_list[-2:]
print(last_two_elements)  


[40, 50]


In [33]:
my_list = [10, 20, 30, 40, 50]
every_other = my_list[::2]
print(every_other)  


[10, 30, 50]


In [34]:
reversed_list = my_list[::-1]
print(reversed_list)  


[50, 40, 30, 20, 10]


In [35]:
text = "Python"
# Accessing a single character
first_char = text[0]
print(first_char)  


P


In [36]:
text = "Python"
# Slicing a substring
substring = text[1:4]
print(substring)  


yth


In [37]:
text = "Python"
# Reversing the string
reversed_text = text[::-1]
print(reversed_text)  


nohtyP


In [40]:
matrix = [[1, 2, 3],
[4, 5, 6],
[7, 8, 9]]
element = matrix[1][2]  
print(element)  



6


In [41]:
my_list = [1, 2, 3]
my_list.append(4)
print(my_list)  


[1, 2, 3, 4]


In [42]:
words = ["hello", "world"]
words.append("Python")
print(words)  


['hello', 'world', 'Python']


In [43]:
my_list = [1, 2, 3]
my_list.extend([4, 5, 6])
print(my_list)  


[1, 2, 3, 4, 5, 6]


In [46]:
fruits = ["apple", "banana"]
fruits.extend(("cherry", "date"))  # You can extend with a tuple
print(fruits)  


['apple', 'banana', 'cherry', 'date']


In [47]:
my_list = [1, 2, 3]
my_list.append([4, 5])
print(my_list)  


[1, 2, 3, [4, 5]]


In [48]:
my_list = [1, 2, 3]
my_list.extend([4, 5])
print(my_list)  


[1, 2, 3, 4, 5]


In [49]:
my_list = [10, 20, 30, 20, 40]
my_list.remove(20)  # Removes the first occurrence of 20
print(my_list)  


[10, 30, 20, 40]


In [50]:
my_list = [10, 20, 30, 40, 50]
last_element = my_list.pop()  # Removes the last element
print(last_element)  
print(my_list)       


50
[10, 20, 30, 40]


In [51]:
specific_element = my_list.pop(1)  # Removes element at index 1
print(specific_element)  
print(my_list)           


20
[10, 30, 40]


In [52]:
my_list = [10, 20, 30, 40, 50]
del my_list[1]  # Deletes element at index 1
print(my_list)  


[10, 30, 40, 50]


In [53]:
# Deleting a slice of elements
del my_list[1:3]  # Deletes elements from index 1 up to, but not including, index 3
print(my_list)    


[10, 50]


In [54]:
my_list = [5, 2, 9, 1, 7]
my_list.sort()  # Sorts in ascending order
print(my_list)  


[1, 2, 5, 7, 9]


In [55]:
my_list.sort(reverse=True)  # Sorts in descending order
print(my_list)  


[9, 7, 5, 2, 1]


In [56]:
my_list = [5, 2, 9, 1, 7]
sorted_list = sorted(my_list)  # Sorts in ascending order
print(sorted_list)  
print(my_list)      


[1, 2, 5, 7, 9]
[5, 2, 9, 1, 7]


In [57]:
my_list = [5, 2, 9, 1, 7]
# Sorting in descending order
sorted_descending = sorted(my_list, reverse=True)
print(sorted_descending)  


[9, 7, 5, 2, 1]


In [58]:
my_list = [5, 2, 9, 1, 7]
my_list.reverse()  # Reverses the order of elements
print(my_list)     


[7, 1, 9, 2, 5]


In [59]:
my_list = [1, 2, 3, 4, 5]
list_length = len(my_list)
print(list_length)  


5


In [60]:
my_string = "Hello, world!"
string_length = len(my_string)
print(string_length)  


13


In [61]:
number = 42
print(type(number))  

text = "Python"
print(type(text))  

items = [1, 2, 3]
print(type(items))  


<class 'int'>
<class 'str'>
<class 'list'>


In [62]:
name = "Alice"
age = 30
print("Name:", name, "Age:", age)  


Name: Alice Age: 30


In [63]:
name = "Alice"
age = 30
# Using formatted strings (f-strings)
print(f"{name} is {age} years old.")  


Alice is 30 years old.


In [64]:
numbers = [10, 20, 30, 40]
total = sum(numbers)
print(total)  


100


In [65]:
numbers = [10, 20, 30, 40]
# Sum with a starting value
total_with_start = sum(numbers, 10)
print(total_with_start)  


110


# Example 3.1 

In [66]:
# Define variables
a = 12
b = 5

# Arithmetic operations
addition = a + b
subtraction = a - b
multiplication = a * b
division = a / b
exponentiation = a ** b
modulus = a % b

# Display results
print("Addition:", addition)
print("Subtraction:", subtraction)
print("Multiplication:", multiplication)
print("Division:", division)
print("Exponentiation:", exponentiation)
print("Modulus:", modulus)


Addition: 17
Subtraction: 7
Multiplication: 60
Division: 2.4
Exponentiation: 248832
Modulus: 2


# Example 3.2

In [67]:
import numpy as np

# Define matrices
A = np.array([[1, 2], [3, 4]])
B = np.array([[5, 6], [7, 8]])

# Matrix operations
matrix_addition = A + B
matrix_subtraction = A - B
elementwise_multiplication = A * B
matrix_multiplication = A @ B

# Display results
print("Matrix Addition:\n", matrix_addition)
print("Matrix Subtraction:\n", matrix_subtraction)
print("Element-wise Multiplication:\n", elementwise_multiplication)
print("Matrix Multiplication:\n", matrix_multiplication)


Matrix Addition:
 [[ 6  8]
 [10 12]]
Matrix Subtraction:
 [[-4 -4]
 [-4 -4]]
Element-wise Multiplication:
 [[ 5 12]
 [21 32]]
Matrix Multiplication:
 [[19 22]
 [43 50]]


# Example 3.3

In [68]:
# Define variables
a = 7
b = 3

# Logical operations
is_equal = (a == b)
is_not_equal = (a != b)
is_greater_than = (a > b)
is_less_than_or_equal = (a <= b)

# Display results
print("Is Equal:", is_equal)
print("Is Not Equal:", is_not_equal)
print("Is Greater Than:", is_greater_than)
print("Is Less Than or Equal:", is_less_than_or_equal)


Is Equal: False
Is Not Equal: True
Is Greater Than: True
Is Less Than or Equal: False
