In [6]:
x = 10      
# Assigns the integer 10 to the variable x
y = 5.5     
# Assigns the float 5.5 to the variable y
name = 'Alice'   
# Assigns a string to the variable name
print(x)
print(y)
print(name)


10
5.5
Alice


In [7]:
x = 10      
y = 5.5     
name = 'Alice'   
print(type(x))    
# Outputs <class 'int'>
print(type(y))    
# Outputs <class 'float'>
print(type(name)) 
# Outputs <class 'str'>


<class 'int'>
<class 'float'>
<class 'str'>


In [8]:
a = 10
b = -3
print(type(a))  
# Outputs <class 'int'>


<class 'int'>


In [9]:
pi = 3.14159
g = -9.8
print(type(pi))  
# Outputs <class 'float'>


<class 'float'>


In [13]:
a = 10
b = -3
sum_result = a + b
product = a * pi
power = 2 ** 3  
# 2 to the power of 3
print(sum_result, product, power)


7 31.4159 8


In [16]:
x = 10   
# Integer
print(x)
y = float(x)
# Converts x to a float (10.0)
print(y)
z = int(y) 
# Converts y back to an integer (10)
print(z)

10
10.0
10


In [19]:
greeting = "Hello, World!"
print(greeting)
quote = 'Python is awesome'
print(quote)
multi_line_text = """This is a
multi-line string"""
print(multi_line_text)

Hello, World!
Python is awesome
This is a
multi-line string


In [23]:
greeting = "Hello, World!"
quote = 'Python is awesome'
hello_world = greeting + " " + quote
print(hello_world)
repeat_text = greeting * 2
print(repeat_text)
first_char = greeting[0]      
print(first_char)
# First character ('H')
substring = greeting[7:12]  
print(substring)
# Slice ('World')

Hello, World! Python is awesome
Hello, World!Hello, World!
H
World


In [26]:
text = " Hello Python "
print(text)
text_upper = text.upper()   
print(text_upper)
text_stripped = text.strip() 
print(text_stripped)
new_text = text.replace("Hello", "Hi")
print(new_text)
index = text.find("Python")
print(index)


 Hello Python 
 HELLO PYTHON 
Hello Python
 Hi Python 
7


In [27]:
path = "C:\\Users\\Username"  
# Windows file path
formatted_text = "Hello\nWorld"  
# New line in string


In [29]:
# Example of basic list creation
numbers = [1, 2, 3, 4, 5]
print(numbers)
mixed_list = [1, "apple", 3.5, True]
print(mixed_list)

[1, 2, 3, 4, 5]
[1, 'apple', 3.5, True]


In [32]:
# Generating a list of numbers from 0 to 9
numbers = list(range(10))  
print(numbers)


[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]


In [35]:
# Generating a list with a custom start, stop, and step
even_numbers = list(range(2, 20, 2))  
print(even_numbers)

[2, 4, 6, 8, 10, 12, 14, 16, 18]


In [37]:
# Creating a list of squares using list comprehension
squares = [x ** 2 for x in range(10)]  
print(squares)


[0, 1, 4, 9, 16, 25, 36, 49, 64, 81]


In [40]:
# Creating a list of even numbers with list comprehension
evens = [x for x in range(10) if x % 2 == 0]  
print(evens)

[0, 2, 4, 6, 8]


In [41]:
# Sample list
fruits = ["apple", "banana", "cherry", "date", "elderberry"]
# Accessing elements by index
print(fruits[0])  
print(fruits[2])  


apple
cherry


In [43]:
# Sample list
fruits = ["apple", "banana", "cherry", "date", "elderberry"]
# Slicing the list
print(fruits[1:4])  
print(fruits[:3])   
print(fruits[2:])   


['banana', 'cherry', 'date']
['apple', 'banana', 'cherry']
['cherry', 'date', 'elderberry']


In [46]:
fruits = ["apple", "banana", "cherry", "date", "elderberry"]
print(fruits[-1])   
print(fruits[-3])   




elderberry
cherry


In [48]:
# Slicing with negative indices
print(fruits[-3:])  
print(fruits[:-2])  


['cherry', 'date', 'elderberry']
['apple', 'banana', 'cherry']


In [49]:
# Sample nested list
nested_list = [["apple", "banana"], ["carrot", "date"], ["eggplant", "fig"]]

# Accessing elements in a nested list
print(nested_list[0])       
print(nested_list[1][0])    
print(nested_list[2][1])    


['apple', 'banana']
carrot
fig


In [50]:
# Sample nested list
nested_list = [["apple", "banana"], ["carrot", "date"], ["eggplant", "fig"]]

# Modifying an element in a nested list
nested_list[0][1] = "blueberry"
print(nested_list)          


[['apple', 'blueberry'], ['carrot', 'date'], ['eggplant', 'fig']]


In [51]:
fruits = ["apple", "banana"]
fruits.append("cherry")
print(fruits)  


['apple', 'banana', 'cherry']


In [54]:
fruits = ["apple", "banana", "cherry"]
fruits.insert(1, "blueberry")
print(fruits)  


['apple', 'blueberry', 'banana', 'cherry']


In [57]:
fruits = ["apple","blueberry", "banana", "cherry"]
fruits.extend(["date", "elderberry"])
print(fruits)  


['apple', 'blueberry', 'banana', 'cherry', 'date', 'elderberry']


In [60]:
fruits = ["apple","blueberry", "banana", "cherry","date", "elderberry"]
fruits.remove("banana")
print(fruits)  


['apple', 'blueberry', 'cherry', 'date', 'elderberry']


In [62]:
fruits = ["apple","blueberry", "cherry","date", "elderberry"]
fruits.pop(1)   
# Removes element at index 1
print(fruits)   


['apple', 'cherry', 'date', 'elderberry']


In [63]:
last_fruit = fruits.pop()  
# Removes and returns the last element
print(last_fruit)  
print(fruits)  


elderberry
['apple', 'cherry', 'date']


In [67]:
fruits = ["apple","cherry","date", "elderberry"]
last_fruit = fruits.pop()  
# Removes and returns the last element
print(last_fruit)  
print(fruits)  


elderberry
['apple', 'cherry', 'date']


In [68]:
fruits = ["apple","cherry","date"]
fruits.clear()
print(fruits)  


[]


In [69]:
# Sample list
fruits = ["apple", "banana", "cherry"]
# Updating an element at a specific index
fruits[1] = "blueberry"
print(fruits)  


['apple', 'blueberry', 'cherry']


In [70]:
# Updating multiple elements by slicing
fruits[0:2] = ["avocado", "blackberry"]
print(fruits)  


['avocado', 'blackberry', 'cherry']


In [71]:
list1 = [1, 2, 3]
list2 = [4, 5, 6]
combined = list1 + list2
print(combined)  


[1, 2, 3, 4, 5, 6]


In [72]:
numbers = [0, 1]
repeated = numbers * 3
print(repeated)  


[0, 1, 0, 1, 0, 1]


In [73]:
fruits = ["apple", "banana", "cherry"]
print("apple" in fruits)  
print("date" in fruits)   


True
False


In [74]:
fruits = ["apple", "banana", "cherry"]
print("date" not in fruits)  


True


In [75]:
numbers = [3, 1, 4, 1, 5]
numbers.sort()  
# Sorts in place
print(numbers)  



[1, 1, 3, 4, 5]


In [76]:
# Using sorted() to create a new sorted list
original = [3, 1, 4, 1, 5]
sorted_numbers = sorted(original)
print(original)        
print(sorted_numbers)  


[3, 1, 4, 1, 5]
[1, 1, 3, 4, 5]


In [78]:
numbers = [1, 2, 3, 4]
numbers.reverse()  
# Reverses in place
print(numbers)  



[4, 3, 2, 1]


In [79]:
# Using reversed() to get a reversed list without modifying the original
original = [1, 2, 3, 4]
reversed_numbers = list(reversed(original))
print(original)          
print(reversed_numbers)  


[1, 2, 3, 4]
[4, 3, 2, 1]


In [80]:
fruits = ["apple", "banana", "cherry"]
print(len(fruits))  


3


In [81]:
numbers = [1, 2, 3, 4]
print(min(numbers))  


1


In [82]:
numbers = [1, 2, 3, 4]
print(max(numbers))  


4


In [83]:
numbers = [1, 2, 2, 3, 4, 2]
print(numbers.count(2))  


3


In [84]:
numbers = [1, 2, 2, 3, 4, 2]
print(numbers.index(3))  


3


In [87]:
# Creating a 3x3 matrix
matrix = [
    [1, 2, 3],
    [4, 5, 6],
    [7, 8, 9]]
print(matrix)

[[1, 2, 3], [4, 5, 6], [7, 8, 9]]


In [88]:
# Accessing elements in the matrix
print(matrix[0][0])  
print(matrix[1][2])  
print(matrix[2][1])  


1
6
8


In [89]:
# Modifying an element
matrix[0][1] = 20
print(matrix)  


[[1, 20, 3], [4, 5, 6], [7, 8, 9]]


In [94]:
identity_matrix = [[1, 0], [0, 1]]
print(identity_matrix)

[[1, 0], [0, 1]]


In [97]:
matrix_a = [[1, 2], [3, 4]]
matrix_b = [[5, 6], [7, 8]]
# Initializing an empty matrix to store the result
result = [ [0, 0], [0, 0]]

# Adding matrices element-wise
for i in range(len(matrix_a)):
    for j in range(len(matrix_a[0])):
        result[i][j] = matrix_a[i][j] + matrix_b[i][j]
print(result)  


[[6, 8], [10, 12]]


In [99]:
my_tuple = (1, "apple", 3.14)
print(my_tuple)

(1, 'apple', 3.14)


In [102]:
# Creating a tuple with multiple elements
my_tuple = (1, "apple", 3.14, True)
print(my_tuple)
# Nested tuple
nested_tuple = (1, ("a", "b"), 3)
print(nested_tuple)

(1, 'apple', 3.14, True)
(1, ('a', 'b'), 3)


In [104]:
# Without the comma, Python interprets this as an integer in parentheses

not_a_tuple = (5)  
print(not_a_tuple)

5


In [107]:
# Adding a comma makes it a tuple

single_element_tuple = (5,)  
print(single_element_tuple)

(5,)


In [108]:
# Basic tuple unpacking
person_info = ("Alice", 30, "Engineer")
name, age, profession = person_info

# Result
print(name)       
print(age)        
print(profession) 


Alice
30
Engineer


In [109]:
x = 5
y = 10
x, y = y, x  # Swaps values of x and y
print(x)  
print(y)  


10
5


In [110]:
my_tuple = ("apple", "banana", "cherry")

# Access the first element
print(my_tuple[0])  



apple


In [111]:
my_tuple = ("apple", "banana", "cherry")

# Access the last element using a negative index
print(my_tuple[-1])  


cherry


In [112]:
my_tuple = (1, 2, 3, 4, 5)

# Slice from index 1 to 3 (excludes index 3)
print(my_tuple[1:3])  



(2, 3)


In [113]:
# Slice from the beginning to index 2 (excludes index 2)
print(my_tuple[:2])  


(1, 2)


In [114]:
# Slice from index 2 to the end
print(my_tuple[2:])  


(3, 4, 5)


In [115]:
nested_tuple = (("a", "b", "c"), (1, 2, 3), ("x", "y", "z"))

# Access the first element of the second tuple
print(nested_tuple[1][0])  


1


In [116]:
nested_tuple = (("a", "b", "c"), (1, 2, 3), ("x", "y", "z"))
# Access the last element of the last tuple
print(nested_tuple[2][-1])  


z


In [117]:
tuple1 = (1, 2, 3)
tuple2 = (4, 5, 6)

# Concatenate tuples
combined_tuple = tuple1 + tuple2
print(combined_tuple)  


(1, 2, 3, 4, 5, 6)


In [118]:
my_tuple = ("apple", "banana")

# Repeat elements in the tuple
repeated_tuple = my_tuple * 3
print(repeated_tuple)  


('apple', 'banana', 'apple', 'banana', 'apple', 'banana')


In [119]:
fruits = ("apple", "banana", "cherry")
# Check if 'apple' is in the tuple
print("apple" in fruits)  


True


In [120]:
fruits = ("apple", "banana", "cherry")
# Check if 'orange' is not in the tuple
print("orange" not in fruits)  


True


In [121]:
numbers = (10, 20, 30, 40, 50)
# Find length of the tuple
print(len(numbers))  


5


In [122]:
# Find the maximum value
print(max(numbers))  


50


In [123]:
# Find the minimum value
print(min(numbers))  


10


In [124]:
my_tuple = (1, 2, 2, 3, 4, 2)

# Count occurrences of 2
print(my_tuple.count(2))  


3


In [125]:
my_tuple = ("apple", "banana", "cherry")

# Find index of 'banana'
print(my_tuple.index("banana"))   


1


In [126]:
my_tuple = (10, 20, 30)

# Length of the tuple
print(len(my_tuple))  


3


In [127]:
numbers = (10, 20, 5, 30)

# Minimum value
print(min(numbers))  


5


In [128]:
numbers = (10, 20, 5, 30)

# Maximum value
print(max(numbers))  


30


In [129]:
numbers = (1, 2, 3, 4)

# Sum of all elements
print(sum(numbers))  


10


In [135]:
# Creating a dictionary directly
my_dictionary = {
    "name": "Alice",
    "age": 25,
    "city": "New York"
}
print(my_dictionary)


{'name': 'Alice', 'age': 25, 'city': 'New York'}


In [136]:
# Creating an empty dictionary
my_dictionary = {}
my_dictionary["name"] = "Alice"
my_dictionary["age"] = 25
my_dictionary["city"] = "New York"
print(my_dictionary)


{'name': 'Alice', 'age': 25, 'city': 'New York'}


In [137]:
squares = {x: x**2 for x in range(1, 6)}
print(squares)  


{1: 1, 2: 4, 3: 9, 4: 16, 5: 25}


In [138]:
keys = ["name", "age", "city"]
values = ["Alice", 25, "New York"]
my_dictionary = dict(zip(keys, values))
print(my_dictionary)  


{'name': 'Alice', 'age': 25, 'city': 'New York'}


In [139]:
list_of_tuples = [("name", "Alice"), ("age", 25), ("city", "New York")]
my_dictionary = dict(list_of_tuples)
print(my_dictionary)  


{'name': 'Alice', 'age': 25, 'city': 'New York'}


In [140]:
my_dictionary = {"name": "Alice", "age": 25, "city": "New York"}
print(my_dictionary["name"])  


Alice


In [144]:
my_dictionary = {"name": "Alice", "age": 25, "city": "New York"}
print(my_dictionary.get("age"))         
print(my_dictionary.get("country", "Not Found"))  



25
Not Found


In [145]:
my_dictionary["age"] = 26
print(my_dictionary)  


{'name': 'Alice', 'age': 26, 'city': 'New York'}


In [146]:
my_dictionary["country"] = "USA"
print(my_dictionary)  


{'name': 'Alice', 'age': 26, 'city': 'New York', 'country': 'USA'}


In [154]:
my_dictionary1 = {"name": "Alice", "age": 25, "city": "New York"}
age = my_dictionary1.pop("age")
print(age)  
print(my_dictionary1)  



25
{'name': 'Alice', 'city': 'New York'}


In [156]:
last_item = my_dictionary1.popitem()
print(last_item)  
print(my_dictionary1)  


('city', 'New York')
{'name': 'Alice'}


In [157]:
my_dictionary2 = {"name": "Alice", "age": 25, "city": "New York"}
del my_dictionary2["city"]
print(my_dictionary2)  


{'name': 'Alice', 'age': 25}


In [158]:
my_dictionary2 = {"name": "Alice", "age": 25, "city": "New York"}
my_dictionary2.clear()
print(my_dictionary2)  


{}


In [159]:
my_dictionary = {"name": "Alice", "age": 25, "city": "New York"}
print(my_dictionary.keys())  


dict_keys(['name', 'age', 'city'])


In [160]:
print(my_dictionary.values())  

dict_values(['Alice', 25, 'New York'])


In [161]:
print(my_dictionary.items())  

dict_items([('name', 'Alice'), ('age', 25), ('city', 'New York')])


In [162]:
my_dictionary.update({"age": 26, "country": "USA"})
print(my_dictionary)  


{'name': 'Alice', 'age': 26, 'city': 'New York', 'country': 'USA'}


In [164]:
age = my_dictionary.pop("age", "Not Found")
print(age)  
print(my_dictionary)  


26
{'name': 'Alice', 'city': 'New York', 'country': 'USA'}


In [165]:
my_dictionary.clear()
print(my_dictionary)  


{}


In [166]:
my_dictionary = {"name": "Alice", "age": 25, "city": "New York"}
print(len(my_dictionary))  


3


In [167]:
print(sorted(my_dictionary))  
print(sorted(my_dictionary, reverse=True))  

['age', 'city', 'name']
['name', 'city', 'age']


In [169]:
students = {
    "student1": {
        "name": "Alice",
        "age": 25,
        "courses": ["Math", "Science"]
    },
    "student2": {
        "name": "Bob",
        "age": 22,
        "courses": ["History", "English"]
    }
}
print(students)

{'student1': {'name': 'Alice', 'age': 25, 'courses': ['Math', 'Science']}, 'student2': {'name': 'Bob', 'age': 22, 'courses': ['History', 'English']}}


In [170]:
# Access the name of student1
print(students["student1"]["name"])  

# Access the list of courses for student2
print(students["student2"]["courses"])  


Alice
['History', 'English']


In [171]:
# Access the first course of student1
print(students["student1"]["courses"][0])  


Math


In [172]:
# Update student1's age
students["student1"]["age"] = 26
print(students["student1"]["age"])  


26


In [173]:
# Add a new field "grade" for student1
students["student1"]["grade"] = "A"
print(students["student1"])  


{'name': 'Alice', 'age': 26, 'courses': ['Math', 'Science'], 'grade': 'A'}


In [174]:
# Delete the "age" key for student2
del students["student2"]["age"]
print(students["student2"])  


{'name': 'Bob', 'courses': ['History', 'English']}


In [175]:
# Delete the entire record for student1
del students["student1"]
print(students)  


{'student2': {'name': 'Bob', 'courses': ['History', 'English']}}


In [176]:
# Safely access a key that might not exist
print(students.get("student1", {}).get("grade", "Not Found"))  


Not Found


In [177]:
# Defining a set with elements
my_set = {1, 2, 3, 4}
print(my_set)  

# Creating an empty set
empty_set = set()


{1, 2, 3, 4}


In [178]:
# Creating a set with unique elements
my_set = {1, 2, 3, 4, 5}
print(my_set)  

# Set with duplicate values
my_set = {1, 2, 2, 3, 4, 4}
print(my_set)  


{1, 2, 3, 4, 5}
{1, 2, 3, 4}


In [179]:
# Creating an empty set
empty_set = set()
print(empty_set)  

# Creating a set using set() with an iterable
my_set = set([1, 2, 3, 4])
print(my_set)  


set()
{1, 2, 3, 4}


In [180]:
# Creating a set from a list with duplicate elements
my_list = [1, 2, 2, 3, 4, 4, 5]
my_set = set(my_list)
print(my_set)  


{1, 2, 3, 4, 5}


In [183]:
# Creating a set from a string
my_string = "hello"
my_set = set(my_string)
print(my_set)  


{'h', 'o', 'l', 'e'}


In [184]:
my_set = {1, 2, 3}
my_set.add(4)
print(my_set)  




{1, 2, 3, 4}


In [185]:
# Attempting to add a duplicate element
my_set.add(3)
print(my_set)  


{1, 2, 3, 4}


In [187]:
my_set = {1, 2, 3}
my_set.update([4, 5, 6])  # Adding multiple elements
print(my_set)  




{1, 2, 3, 4, 5, 6}


In [188]:
# Adding elements from another set
my_set.update({7, 8})
print(my_set)  


{1, 2, 3, 4, 5, 6, 7, 8}


In [189]:
my_set = {1, 2, 3, 4}
my_set.remove(3)
print(my_set)  




{1, 2, 4}


In [190]:
# Attempting to remove an element that is not in the set
my_set.remove(5)  


KeyError: 5

In [191]:
my_set = {1, 2, 3, 4}
my_set.discard(3)
print(my_set)  




{1, 2, 4}


In [192]:
# Attempting to discard an element that is not in the set
my_set.discard(5)  # No error is raised
print(my_set)  


{1, 2, 4}


In [193]:
my_set = {1, 2, 3, 4}
removed_element = my_set.pop()
print(removed_element)  
print(my_set)  




1
{2, 3, 4}


In [194]:
# Attempting to pop from an empty set
empty_set = set()
empty_set.pop()  


KeyError: 'pop from an empty set'

In [195]:
my_set = {1, 2, 3, 4}
my_set.clear()
print(my_set)  


set()


In [197]:
set1 = {1, 2, 3}
set2 = {3, 4, 5}

# Using | operator
union_set = set1 | set2
print(union_set)  




{1, 2, 3, 4, 5}


In [198]:
# Using union() method
union_set = set1.union(set2)
print(union_set)  


{1, 2, 3, 4, 5}


In [199]:
set1 = {1, 2, 3}
set2 = {3, 4, 5}

# Using & operator
intersection_set = set1 & set2
print(intersection_set)  




{3}


In [200]:
# Using intersection() method
intersection_set = set1.intersection(set2)
print(intersection_set)  


{3}


In [201]:
set1 = {1, 2, 3}
set2 = {3, 4, 5}

# Using - operator
difference_set = set1 - set2
print(difference_set)  




{1, 2}


In [202]:
# Using difference() method
difference_set = set1.difference(set2)
print(difference_set)  


{1, 2}


In [203]:
set1 = {1, 2, 3}
set2 = {3, 4, 5}

# Using ^ operator
symmetric_difference_set = set1 ^ set2
print(symmetric_difference_set)  


{1, 2, 4, 5}


In [204]:
# Using symmetric_difference() method
symmetric_difference_set = set1.symmetric_difference(set2)
print(symmetric_difference_set)  


{1, 2, 4, 5}


In [205]:
set1 = {1, 2, 3}
print(2 in set1)  
print(4 in set1)  


True
False


In [206]:
set1 = {1, 2, 3}
print(4 not in set1)  
print(2 not in set1)  


True
False


In [2]:
set_a = {1, 2, 3}
set_b = {3, 4, 5}
union_set = set_a.union(set_b)  
print(union_set)

{1, 2, 3, 4, 5}


In [4]:
set_a = {1, 2, 3}
set_b = {3, 4, 5}
intersection_set = set_a.intersection(set_b)  
print(intersection_set)

{3}


In [6]:
set_a = {1, 2, 3}
set_b = {3, 4, 5}
difference_set = set_a.difference(set_b)  
print(difference_set)

{1, 2}


In [9]:
set_a = {1, 2, 3}
set_b = {3, 4, 5}
symmetric_difference_set = set_a.symmetric_difference(set_b)  
print(symmetric_difference_set)

{1, 2, 4, 5}


In [11]:
set_a = {1, 2}
set_b = {1, 2, 3, 4}
is_subset = set_a.issubset(set_b)  
print(is_subset)

True


In [12]:
set_a = {1, 2, 3, 4}
set_b = {1, 2}
is_superset = set_a.issuperset(set_b)  
print(is_superset)

True


In [15]:
set_a = {1, 2}
set_b = {3, 4}
is_disjoint = set_a.isdisjoint(set_b)  
print(is_disjoint)

True


# Example 1

In [17]:
import numpy as np

A = np.array([[1, 2], [3, 4]])
B = np.array([[5, 6], [7, 8]])

# Transpose
A_transpose = A.T

# Element-wise multiplication
C_elementwise = A * B

# Matrix multiplication
C_matrix = A @ B

print("Transpose:\n", A_transpose)
print("Element-wise multiplication:\n", C_elementwise)
print("Matrix multiplication:\n", C_matrix)


Transpose:
 [[1 3]
 [2 4]]
Element-wise multiplication:
 [[ 5 12]
 [21 32]]
Matrix multiplication:
 [[19 22]
 [43 50]]


# Example 2

In [18]:
str1 = 'Hello'
str2 = 'World'

# Concatenate strings
combined_str = str1 + ' ' + str2

# Convert to uppercase
upper_str = combined_str.upper()

# Find position of substring
pos = combined_str.find('World')

print("Concatenated string:", combined_str)
print("Uppercase string:", upper_str)
print('Position of "World":', pos)


Concatenated string: Hello World
Uppercase string: HELLO WORLD
Position of "World": 6


# Example 3

In [21]:
# Defining variables
int_var = 10            # Integer
float_var = 3.14        # Float
str_var = "Hello"       # String

# Displaying variables
print(int_var)
print(float_var)
print(str_var)



10
3.14
Hello


# Example 4

In [22]:
# Data types in Python
int_var = 5                    # Integer
float_var = 2.718              # Float
str_var = "Python"             # String

# Checking types
print(type(int_var))
print(type(float_var))
print(type(str_var))


<class 'int'>
<class 'float'>
<class 'str'>


# Example 5

In [23]:
# Define a list
array = [1, 2, 3, 4, 5]

# Indexing and modifying an element
second_element = array[1]     # Access second element
array[2] = 10                 # Modify third element

print(array)


[1, 2, 10, 4, 5]


# Example 6

In [24]:
# Define and concatenate strings
str1 = "Hello, "
str2 = "Python"
combined_str = str1 + str2

# Convert to uppercase and find substring position
upper_str = combined_str.upper()
position = combined_str.find("Python")

print(combined_str)
print(upper_str)
print(position)


Hello, Python
HELLO, PYTHON
7


# Example 7

In [25]:
# Define a list with mixed types
mixed_list = [42, "Data", [1, 2, 3]]

# Access elements
first_element = mixed_list[0]
second_element = mixed_list[1]

print(mixed_list)
print(first_element)
print(second_element)


[42, 'Data', [1, 2, 3]]
42
Data


# Example 8

In [26]:
# Define a dictionary with multiple keys
student = {
    "name": "Alice",
    "age": 21,
    "grade": 85
}

# Access and modify values
print(student["name"])
student["age"] = 22
print(student)


Alice
{'name': 'Alice', 'age': 22, 'grade': 85}


# Example 9

In [29]:
import math

# Define variables for radius and height
radius = 5
height = 10

# Calculate volume and surface area
volume = math.pi * radius**2 * height
surface_area = 2 * math.pi * radius * (radius + height)

print(f"Volume of the cylinder: {volume}")
print(f"Surface area of the cylinder: {surface_area}")


Volume of the cylinder: 785.3981633974483
Surface area of the cylinder: 471.23889803846896


# Example 10

In [30]:
import numpy as np

# Define points as a 2D array
points = np.array([[3, 4], [5, 12], [8, 15]])

# Calculate distances from the origin
distances = np.sqrt(np.sum(points**2, axis=1))

print("Points:\n", points)
print("Distances from origin:\n", distances)


Points:
 [[ 3  4]
 [ 5 12]
 [ 8 15]]
Distances from origin:
 [ 5. 13. 17.]


# Example 11

In [31]:
# Define a string with a mathematical expression
expression = "3 * (4 + 5) - 2**3"

# Evaluate the expression
result = eval(expression)

# Display result with formatted string
print(f"The result of {expression} is: {result}")


The result of 3 * (4 + 5) - 2**3 is: 19


# Example 12

In [32]:
import numpy as np

# Define matrices A and B
A = np.array([[1, 2], [3, 4]])
B = np.array([[5, 6], [7, 8]])

# Perform matrix operations
sum_matrix = A + B
difference_matrix = A - B
product_matrix = A @ B

print("Sum of A and B:\n", sum_matrix)
print("Difference of A and B:\n", difference_matrix)
print("Product of A and B:\n", product_matrix)


Sum of A and B:
 [[ 6  8]
 [10 12]]
Difference of A and B:
 [[-4 -4]
 [-4 -4]]
Product of A and B:
 [[19 22]
 [43 50]]


# Example 13

In [33]:
import numpy as np

# Define a matrix
A = np.array([[4, 7], [2, 6]])

# Calculate the determinant
determinant = np.linalg.det(A)

# Calculate the inverse if the matrix is invertible
if determinant != 0:
    inverse_A = np.linalg.inv(A)
    print("Inverse of A:\n", inverse_A)
else:
    print("Matrix A is singular and has no inverse.")

print("Determinant of A:", determinant)


Inverse of A:
 [[ 0.6 -0.7]
 [-0.2  0.4]]
Determinant of A: 10.000000000000002


# Example 14

In [34]:
import numpy as np

# Define matrix A and vector B
A = np.array([[3, 2], [1, 2]])
B = np.array([8, 6])

# Solve for X in AX = B
X = np.linalg.solve(A, B)

print("Solution for X:", X)


Solution for X: [1.  2.5]


# Example 15

In [35]:
import numpy as np

# Define a matrix
A = np.array([[4, -2], [1, 1]])

# Calculate eigenvalues and eigenvectors
eigenvalues, eigenvectors = np.linalg.eig(A)

print("Eigenvalues of A:", eigenvalues)
print("Eigenvectors of A:\n", eigenvectors)


Eigenvalues of A: [3. 2.]
Eigenvectors of A:
 [[0.89442719 0.70710678]
 [0.4472136  0.70710678]]


# Example 16

In [36]:
import numpy as np
from scipy.linalg import null_space

# Define a matrix
A = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])

# Calculate the rank
matrix_rank = np.linalg.matrix_rank(A)

# Calculate the null space
null_space_A = null_space(A)

print("Rank of A:", matrix_rank)
print("Null space of A:\n", null_space_A)


Rank of A: 2
Null space of A:
 [[-0.40824829]
 [ 0.81649658]
 [-0.40824829]]


# Example 17

In [37]:
import numpy as np

# Define matrices A and B
A = np.array([[1, 2, 3], [4, 5, 6]])
B = np.array([[7, 8], [9, 10], [11, 12]])

# Perform matrix multiplication
C = np.dot(A, B)

# Calculate the transpose of the result
C_transpose = C.T

print("Matrix A * B:\n", C)
print("Transpose of the product:\n", C_transpose)


Matrix A * B:
 [[ 58  64]
 [139 154]]
Transpose of the product:
 [[ 58 139]
 [ 64 154]]


# Example 18

In [38]:
import numpy as np

# Define a square matrix
A = np.array([[2, -1, 0], [-1, 2, -1], [0, -1, 2]])

# Calculate the trace of the matrix
trace_A = np.trace(A)

print("Trace of A:", trace_A)


Trace of A: 6


# Example 19

In [39]:
import numpy as np

# Define a square matrix
A = np.array([[2, 1], [1, 3]])

# Raise matrix to the third power
A_cubed = np.linalg.matrix_power(A, 3)

print("A cubed:\n", A_cubed)


A cubed:
 [[15 20]
 [20 35]]


# Example 20

In [40]:
import numpy as np
from scipy.linalg import expm

# Define a square matrix
A = np.array([[0, 1], [-1, 0]])

# Calculate the matrix exponential
expA = expm(A)

print("Matrix exponential of A:\n", expA)


Matrix exponential of A:
 [[ 0.54030231  0.84147098]
 [-0.84147098  0.54030231]]
